version: "3.8"

services: 
  web:
    build: .
    depends_on:
      - verdaccio
    user: root
    ports: 
      - "${PORT_ADMIN}:${PORT_ADMIN}"
    volumes:
      - verdaccio-data:/verdaccio/storage/data
      - git-repo:/verdaccio/storage/.git
      - ./verdaccio/storage/.gitignore:/verdaccio/storage/.gitignore
      - patches:/patches
    environment:
      - PORT_ADMIN
  verdaccio:
    image: verdaccio/verdaccio
    user: root
    volumes:
      - verdaccio-data:/verdaccio/storage/data
      - ./verdaccio/conf/config.yaml:/verdaccio/conf/config.yaml

volumes:
  verdaccio-data:
  git-repo:
  patches:
